- name: Ensure psutil is installed
  pip:
    name: psutil

- name: Apply dconf settings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  # Apply to current user, not root
  become: false
  loop: "{{ dconf_settings }}"