- import_tasks: roles/desktop/tasks/packages/steps/chrome.yml
- import_tasks: roles/desktop/tasks/packages/steps/vscode.yml
- import_tasks: roles/desktop/tasks/packages/steps/java.yml
- import_tasks: roles/desktop/tasks/packages/steps/apt.yml
- import_tasks: roles/desktop/tasks/packages/steps/zoom.yml

- import_tasks: roles/desktop/tasks/pin.yml
- import_tasks: roles/desktop/tasks/dconf.yml

- import_role:
    name: roles/desktop/notion 