- import_tasks: roles/desktop/tasks/packages/steps/git-cred-helper.yml
- import_tasks: roles/desktop/tasks/packages/steps/chrome.yml
- import_tasks: roles/desktop/tasks/packages/steps/vscode.yml
- import_tasks: roles/desktop/tasks/packages/steps/java.yml
- import_tasks: roles/desktop/tasks/packages/steps/apt.yml
- import_tasks: roles/desktop/tasks/packages/steps/zoom.yml
  tags:
    - zoom
    - initial
    - never # don't enable by default because it downloads the deb every time!
- import_tasks: roles/desktop/tasks/packages/steps/beeper.yml

- import_tasks: roles/desktop/tasks/pin.yml
- import_tasks: roles/desktop/tasks/dconf.yml

- import_role:
    name: roles/desktop/notion

- import_role:
    name: roles/desktop/nerd-fonts

- import_role:
    name: vmware.vmware-workstation
  tags:
    - vmware
    - initial
    - never

- import_role:
    name: roles/desktop/nvidia-cuda

- import_role:
    name: roles/desktop/displaylink-driver