- import_tasks: roles/desktop/tasks/packages/steps/dropbox.yml
  tags:
    - dropbox
    - never # most people probably don't want drop box
- import_tasks: roles/desktop/tasks/packages/steps/git-cred-helper.yml
- import_tasks: roles/desktop/tasks/packages/steps/chrome.yml
- import_tasks: roles/desktop/tasks/packages/steps/vscode.yml
- import_tasks: roles/desktop/tasks/packages/steps/java.yml
- import_tasks: roles/desktop/tasks/packages/steps/apt.yml
- import_tasks: roles/desktop/tasks/packages/steps/zoom.yml
  tags:
    - zoom
    - initial
    - never # don't enable by default because it downloads the deb every time!
- import_tasks: roles/desktop/tasks/packages/steps/warp.yml
  tags:
    - warp
    - initial
    - never


- import_tasks: roles/desktop/tasks/packages/steps/beeper.yml

# Fix Print Screen key wrongly mapped to Tools
- import_tasks: roles/desktop/tasks/bookmarks.yml
- import_tasks: roles/desktop/tasks/modmap.yml
- import_tasks: roles/desktop/tasks/pin.yml
- import_tasks: roles/desktop/tasks/dconf.yml
- import_tasks: roles/desktop/tasks/gdm.yml
  tags:
    - gdm
    - never

- import_role:
    name: roles/desktop/notion

- import_role:
    name: roles/desktop/nerd-fonts

- import_role:
    name: vmware.vmware-workstation
  tags:
    - vmware
    - initial
    - never

- import_role:
    name: roles/desktop/nvidia-cuda

- import_role:
    name: roles/desktop/displaylink-driver

- import_role:
    name: roles/desktop/wine

- import_role:
    name: roles/desktop/canon-printer-driver
  tags:
    - canon