- name: Force systemd not to suspend for unknown reasons
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf.d/10-no-stupid-suspend.conf
    line: HandleLidSwitchExternalPower=ignore
    create: yes