- name: Force systemd not to suspend for unknown reasons
  ansible.builtin.blockinfile:
    path: /etc/systemd/logind.conf.d/10-no-stupid-suspend.conf
    block: |
      [Login]
      HandleLidSwitchExternalPower=ignore
    create: yes