- name: Install base apt packages
  ansible.builtin.apt:
    name: "{{ base_apt_packages }}"
- name: Install latex apt packages
  ansible.builtin.apt:
    name: "{{ latex_apt_packages }}"
- name: Install research apt packages
  ansible.builtin.apt:
    name: "{{ research_apt_packages }}"
- name: Install snap packages
  community.general.snap:
    name: "{{ snap_packages }}"