- name: Install base apt packages
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
      - curl
      - htop
      - tree
      - tmux
      - ca-certificates
      - python3-pip
      - build-essential
