- name: Install hashicorp apt key
  shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  notify: Apt update

- name: Add hashicorp apt repository
  lineinfile:
    create: true
    line: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main
    path: /etc/apt/sources.list.d/hashicorp.list
  notify: Apt update

- meta: flush_handlers

- name: Install packer from hashicorp apt repository
  apt:
    name: packer