- name: Install nvidia cuda-keyring deb
  apt:
    deb: "{{ cuda_keyring_deb }}"
  notify: Apt update

- name: Flush handlers
  meta: flush_handlers

- name: Install nvidia kernel drivers (closed)
  apt:
    name:
      - "cuda-drivers-{{ nvidia_driver_version }}"
  when: not nvidia_use_open_drivers

- name: Install nvidia kernel drivers (open)
  apt:
    name:
      - "cuda-toolkit-{{ cuda_toolkit_version }}"
      - "nvidia-driver-{{ nvidia_driver_version }}-open"
      - "cuda-drivers-{{ nvidia_driver_version }}"
  when: nvidia_use_open_drivers