- name: Download beeper
  get_url:
    url: https://api.beeper.com/desktop/download/linux/x64/stable/com.automattic.beeper.desktop
    dest: /usr/local/bin/beeper
    mode: '0755'

- name: Install fuse
  package:
    name: libfuse2
    state: present

- name: Add .desktop file
  copy:
    src: beeper.desktop
    dest: /usr/share/applications/beeper.desktop

- name: Autostart beeper
  file:
    src: /usr/share/applications/beeper.desktop
    dest: "/home/{{ user_name }}/.config/autostart/beeper.desktop"
    state: link
