- name: Install Java
  import_role:
    name: temurin
  vars:
    temurin_packages:
      - adoptium-ca-certificates
      - temurin-17-jdk
      - temurin-21-jdk

- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/temurin-21-jdk-amd64'

- name: Set java alternative
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/temurin-21-jdk-amd64/bin/java

- name: Set javac alternative
  community.general.alternatives:
    name: javac
    path: /usr/lib/jvm/temurin-21-jdk-amd64/bin/javac